export type DocBlock = { heading: string; body: string; points?: string[]; flow?: string[]; table?: { columns: string[]; rows: string[][] }; code?: string; note?: string };
export type DocPage = { slug: string; title: string; group: string; eyebrow: string; summary: string; takeaway: string; blocks: DocBlock[] };
const page = (slug: string, title: string, group: string, summary: string, takeaway: string, blocks: DocBlock[]): DocPage => ({ slug, title, group, eyebrow: group.toUpperCase(), summary, takeaway, blocks });
const block = (heading: string, body: string, extra: Partial<DocBlock> = {}): DocBlock => ({ heading, body, ...extra });

export const docs: DocPage[] = [
  page("overview", "Overview", "Start here", "A living intelligence layer for the household.", "Household Intelligence models changing household state, traces consequences, proposes bounded actions, and checks outcomes against reality.", [
    block("Five-second understanding", "An intelligent household state layer that understands how changes propagate across people, resources, schedules and obligations."),
    block("Thirty-second understanding", "A receipt changes inventory. A dinner plan changes ingredient demand. A shortage changes a purchase decision. The system connects those events, shows the reason chain, asks before consequential action, and reconciles the result. Kitchen intelligence is the first proof point; the same state-and-dependency model can extend to other domains."),
    block("The operating loop", "The system turns observations into accountable state transitions. The diagram shows the conceptual architecture, not a claim that every layer is production complete.", { flow: ["HOUSEHOLD STATE", "RELATIONSHIP GRAPH", "RIPPLE ENGINE", "SIMULATION", "AGENT ACTION", "REAL-WORLD VERIFICATION", "UPDATED STATE"] }),
    block("Why this is different", "A chat answer ends at advice. Household Intelligence keeps a canonical record, calculates consequences through deterministic rules, requests approval, and records whether an external action worked."),
    block("Implementation snapshot", "The repository currently contains a React/Vite app, Fastify API, shared Zod contracts, deterministic kitchen and ripple engines, receipt/voice/action workflows, and OpenAI, Sarvam and Snapserve adapters. Runtime household state is currently persisted to a JSON file or ephemeral storage. A Prisma schema describes the planned PostgreSQL model; the live runtime does not yet use PostgreSQL as its canonical store.", { note: "Status is based on the checked-in code, not a production deployment audit." }),
  ]),
  page("executive-summary", "Executive Summary", "Start here", "The missing abstraction is household state.", "The initial wedge is kitchen intelligence; the architectural thesis is cross-domain consequence propagation.", [
    block("Problem and insight", "Calendars, shopping lists, bills, documents and physical resources each hold a slice of reality. A change in one place rarely updates the others. The user becomes the integration layer. The missing abstraction is a shared, current household state with explicit relationships."),
    block("Solution and signature mechanism", "Events update state; the Ripple Engine traverses dependencies and computes affected entities. A what-if fork compares alternatives without mutating current state. Approved actions are executed through bounded tools, then verified through observations.", { flow: ["OBSERVE", "SIMULATE", "ACT", "VERIFY"] }),
    block("Value and audience", "The product aims to reduce manual coordination, unnecessary purchases and missed obligations for multi-person households, caregivers and busy families. Initial value is clearest when a receipt, meal plan and purchase decision intersect."),
    block("Technology and business thesis", "React/Vite and Fastify provide the current app and API. TypeScript domain services perform calculations; provider adapters support language, speech and outbound calls. Subscription, premium automation and transaction revenue are hypotheses requiring validation, not current revenue."),
  ]),
  page("problem", "The Problem", "Product", "Fragmented state, hidden dependencies, constantly changing reality.", "The burden is coordination, not simple forgetfulness.", [
    block("A household is a coupled system", "A dinner guest count affects ingredients, inventory, shopping, budget and timing. A vehicle appointment affects availability, documents and travel. Yet each application sees only one fragment. Physical state also changes between app updates.", { flow: ["Calendar · Inventory · Bills · Documents · Vehicles · Preferences", "Disconnected records", "No shared household model", "No consequence propagation", "Manual coordination by people"] }),
    block("Why familiar assumptions fail", "Existing tools often assume independent tasks, manual entry, static state, a user who already knows the next action, and recommendations that need no outcome check. In a shared household, multiple people act, quantities move, plans change, and external services may fail."),
    block("Cost of fragmentation", "The results can include duplicate purchases, stale pantry quantities, missed renewal steps, last-minute shortages and cognitive load. These are product hypotheses to measure; this prototype does not claim quantified savings."),
  ]),
  page("product", "The Product", "Product", "The intelligence layer between a household and its software and services.", "Its unit of value is a verified state transition with an explainable consequence chain.", [
    block("What it does", "Household Intelligence receives an event, validates or clarifies it, updates a household model, computes downstream effects, presents options and executes approved actions. It keeps the history needed to explain why a recommendation appeared."),
    block("Category comparison", "These categories can overlap; the distinction describes the intended architectural combination.", { table: { columns: ["Category", "Primary job", "Typical gap"], rows: [["Assistant", "Answer or draft", "No durable canonical household state"], ["Task manager", "Track explicit tasks", "Weak causal propagation"], ["Inventory app", "Track stock", "Limited cross-domain obligations"], ["Smart-home system", "Observe/control devices", "Limited planning across services"], ["Household Intelligence", "Model state → ripple → simulate → act → verify", "Still a prototype with limited domains"]] } }),
    block("Product boundaries", "A user remains the authority for consequential decisions. The agent cannot make arbitrary purchases or mutate state from an unvalidated language response."),
  ]),
  page("core-innovation", "Core Innovation", "Product", "Five mechanisms form one accountable system.", "AI interpretation is useful; the defensible product idea is state, dependencies, deterministic consequences and verification together.", [
    block("1 / Persistent household state", "A durable model records resources, people, events and obligations as current facts with provenance. Ordinary application data tends to be scoped to one workflow; household state is shared across workflows and must survive an agent conversation."),
    block("2 / Relationship graph", "Typed edges connect entities so a change has a traceable route to consequences.", { flow: ["Person", "Preference", "Meal", "Recipe", "Ingredient", "Inventory", "Purchase", "Budget"] }),
    block("3 / Ripple Engine", "Rules traverse relevant relationships and calculate effects. A dinner guest change can produce revised recipe quantities, shortages and candidate actions, with the calculation performed by TypeScript services."),
    block("4 / What-if simulation", "An isolated state fork applies a hypothetical change. The system compares its output with current state and discards the fork unless a separate authorized command commits a real change."),
    block("5 / Closed-loop verification", "Execution produces an expected outcome. Receipts, transcripts, delivery confirmations or sensor observations can then confirm or challenge it. A mismatch becomes an explicit reconciliation task."),
    block("Why AI alone is insufficient", "The language model interprets and explains. The system owns state, calculations, permissions, execution and auditability. A fluent answer cannot replace inventory arithmetic, approval binding or a real-world observation."),
  ]),
  page("how-it-works", "How It Works", "Product", "A complete event-to-outcome pipeline.", "Every consequential transition has a component, evidence and approval boundary.", [
    block("End-to-end path", "Each stage has a defined input and output. Language models appear at interpretation and explanation; deterministic services own arithmetic and state transitions.", { flow: ["INPUT", "EVENT INGESTION", "STATE UPDATE", "RELATIONSHIP TRAVERSAL", "RIPPLE ANALYSIS", "SIMULATION", "PLAN", "USER APPROVAL", "AGENT EXECUTION", "OBSERVATION", "VERIFICATION", "STATE RECONCILIATION"] }),
    block("Stage responsibilities", "Approval is required before consequential external execution. A hypothetical simulation does not itself commit inventory.", { table: { columns: ["Stage", "Input → output", "Processor / AI / approval"], rows: [["Ingest", "Voice, receipt or form → normalized event", "API + extractor; AI optional; no approval"], ["Update", "Validated event → state transition", "State service; deterministic"], ["Trace + ripple", "Changed entity → affected graph + differences", "Domain engine; deterministic"], ["Simulate + plan", "Candidate change → comparison + action proposal", "State fork + planner; AI may explain"], ["Ask + act", "Proposal → bounded tool call", "Approval token + agent; explicit approval"], ["Observe + verify", "External outcome → reconciled state", "Adapter + verification service; review on mismatch"]] } }),
  ]),
  page("user-experience", "User Experience", "Product", "Desktop explains systems; mobile captures moments.", "The surfaces are shaped by context of use, not merely screen width.", [
    block("Desktop workspace", "The larger surface supports household overview, causal ripple views, current-versus-simulated comparisons, action approvals, activity history and configuration. Judges can inspect the reason behind each recommendation."),
    block("Mobile companion", "The phone prioritizes receipt capture, voice input, quick state edits, timely alerts and approval decisions. Touch targets and short flows matter because the observation usually happens while shopping, cooking or travelling."),
    block("Shared design contract", "Both surfaces expose the same household model through the API. Loading, empty, error and partial-data states should be explicit; an uncertain extraction must be reviewable before inventory changes."),
  ]),
  page("use-cases", "Use Cases", "Product", "One method, several household domains.", "Kitchen is the implemented proof point; other chains illustrate expansion paths.", [
    block("Kitchen intelligence · current prototype", "Meal or receipt input → inventory state → recipe/ingredient dependencies → shortage ripple → purchase proposal → receipt or delivery verification. The flow includes serving scaling, reservation/consumption, expiry awareness and review before committed changes."),
    block("Vehicle intelligence · exploratory", "Mileage or service event → vehicle state → service interval and document dependencies → due work → booking proposal → service record verification."),
    block("Document intelligence · exploratory", "Document upload or expiry date → document state → obligation and appointment dependencies → renewal plan → submitted/issued document verification."),
    block("Subscriptions and scheduling · exploratory", "Renewal or event change → usage/availability state → payment, travel and preparation dependencies → cancellation or rescheduling candidate → provider or calendar outcome verification."),
    block("Budget-aware planning · planned", "A plan → required resources → priced purchase candidates → budget effect → approved spend → receipt reconciliation. Cost figures must be sourced from a real quote or labeled estimates."),
  ]),
  page("kitchen-intelligence", "Kitchen Intelligence", "Product", "A complete case study from spoken intent to verified stock.", "The kitchen scenario demonstrates how language, deterministic arithmetic, approval and reconciliation work together.", [
    block("The request", "A person says, ‘We’re cooking biryani for 10 people tonight.’ Voice or text intake extracts dish, servings and time as structured candidate fields. The person can review ambiguity before committing a meal plan.", { table: { columns: ["Field", "Extracted value", "Role"], rows: [["Dish", "Biryani", "Recipe lookup"], ["Servings", "10", "Scaling input"], ["Time", "Tonight", "Planning context"]] } }),
    block("From recipe to shortage", "The recipe supplies base ingredient quantities. Deterministic scaling calculates requirements for 10 servings. The inventory engine compares required quantity against available on-hand stock, reservations and incoming stock. Any deficit becomes a purchase candidate with an evidence chain.", { flow: ["RECIPE", "INGREDIENT REQUIREMENTS", "INVENTORY", "AVAILABLE QUANTITY", "SHORTAGE", "PURCHASE", "COST ESTIMATE", "BUDGET IMPACT"] }),
    block("What if 12 people come?", "The system forks current state, applies 12 servings, and compares it with the 10-person plan. The difference shows only additional ingredients, stock impact and purchase requirement. Illustrative values should come from the recipe and current pantry; this documentation does not invent quantities or prices.", { table: { columns: ["Comparison", "Current state", "Simulated state"], rows: [["Guests", "10", "12"], ["Recipe demand", "Scaled for 10", "Scaled for 12"], ["Inventory", "Unchanged", "Unchanged in real state"], ["Purchase", "Current shortage", "Incremental shortage"], ["Budget", "Current estimate", "Difference from current"]] } }),
    block("Approval to observation", "After reviewing the reason chain, the user approves a specific proposal. The execution adapter may call a vendor when live credentials are configured, or show a labeled simulator state. An incoming receipt or delivery observation is reconciled against the expectation; confirmed quantities update inventory. A future calibrated sensor could challenge the digital count."),
    block("What is implemented today", "The repository has receipt extraction and confirmation, meal simulation and commitment, counterfactual ripple routes, action approval/execution, delivery reconciliation, and provider adapters. End-to-end provider success is environment dependent; physical sensing and PostgreSQL persistence remain planned."),
  ]),
  page("system-architecture", "System Architecture", "Architecture", "A layered event, state and action architecture.", "The core engine is separate from provider adapters and user interfaces.", [
    block("Layer map", "Arrows represent intended information flow. Some layers have prototype implementations while database and physical sensing remain architectural targets.", { flow: ["CLIENT  Desktop web · Mobile web · Voice", "API  Fastify · Authentication boundary · Event ingestion", "INTELLIGENCE  Extraction · Planning · Explanation", "CORE  State · Relationships · Ripple · Simulation · Policy", "AGENT  Orchestration · Approval · Tool execution · Tracking", "DATA  Runtime file store now · PostgreSQL schema planned", "EXTERNAL  OpenAI · Sarvam · Snapserve", "PHYSICAL  Raspberry Pi · Load cell concept"] }),
    block("Control path", "An input becomes a validated event before a domain engine changes state. A proposed external action moves through permissions and approval. The adapter returns an outcome that can be reconciled with the original expectation."),
  ]),
  page("technical-architecture", "Technical Architecture", "Architecture", "Implementation status matters as much as the stack diagram.", "This repository is a substantial prototype, not a claim of finished production infrastructure.", [
    block("Current code", "React 19, TypeScript, Vite, TanStack Router/Query and Tailwind power the web app. Fastify exposes REST routes. Shared Zod contracts define payloads. Domain TypeScript services calculate inventory, meals, ripple effects and forecasts. OpenAI, Sarvam and Snapserve adapters exist and depend on server-side configuration."),
    block("Prepared or planned", "The Prisma schema defines households, members, resources, inventory lots, recipes, events, relationships, actions, outcomes and audit logs. Runtime state currently uses a JSON-backed HouseholdStore, with ephemeral storage possible in hosted environments. PostgreSQL migration and pgvector retrieval are planned, not active runtime claims."),
    block("Future physical layer", "Raspberry Pi and load-cell observations are a design for closing the physical state loop. There is no claim here that a sensor pipeline is currently deployed."),
    block("Why these technologies", "TypeScript and Zod keep contracts aligned across layers; Fastify handles typed HTTP workflows; relational storage fits transactional state and audit history; vectors could support semantic lookup without becoming the source of truth; provider adapters isolate language, voice and execution services."),
  ]),
  page("data-architecture", "Data Architecture", "Architecture", "State, history and observations serve different jobs.", "An observation can challenge state; it does not silently become a trusted fact.", [
    block("Conceptual entities", "The schema currently models households, members, resources, lots, receipts, recipes, meal plans, events, relationships, obligations, forecasts, actions, outcomes, agent traces, snapshots and audit logs. Users, vehicles, documents and subscriptions are broader-domain concepts for later schema work.", { flow: ["HOUSEHOLD → MEMBERS", "HOUSEHOLD → RESOURCES → INVENTORY LOTS", "RECIPE → INGREDIENTS → RESOURCES", "EVENT → RELATIONSHIPS → OBLIGATIONS", "ACTION → APPROVAL → OUTCOME → AUDIT"] }),
    block("Four records to keep separate", "Current state answers what is believed now. Event history says what happened. Relationships explain why a change matters. Observations are signals from people, integrations or devices that may confirm or contradict state."),
    block("Provenance and confidence", "A robust state field should carry value, source, timestamp and confidence. The prototype carries confidence on selected events/extractions; a universal provenance model across every entity remains future work."),
  ]),
  page("ai-architecture", "AI Architecture", "Architecture", "Language interpretation is bounded by structured contracts.", "AI does not own quantities, permissions or persistence.", [
    block("AI responsibilities", "Natural language and receipt interpretation, structured extraction, contextual reasoning, answer generation and multilingual voice interaction where configured. Semantic retrieval is a planned extension, not the canonical data store.", { flow: ["USER LANGUAGE", "AI INTERPRETATION", "STRUCTURED EVENT", "DETERMINISTIC SYSTEM", "STATE · RIPPLE · SIMULATION", "AI EXPLANATION", "USER"] }),
    block("Deterministic responsibilities", "Inventory arithmetic, serving scaling, shortage and budget calculations, state persistence, validation, permission checks, transaction boundaries, action logging and verification belong to services. The model may suggest an intent; schemas and domain rules decide whether it is usable."),
    block("Hallucination controls", "Constrain extraction to schema, reject unsupported fields, show low-confidence items for review, cite the state/evidence chain in proposals, and never execute a consequential tool call from a raw model response. Provider failure should fall back to a bounded deterministic path or a clear error."),
  ]),
  page("agentic-architecture", "Agentic Architecture", "Architecture", "Agents coordinate; tools enforce boundaries.", "The agent does not receive unrestricted household or vendor control.", [
    block("Lifecycle", "Agent workflows route an observation through interpretation, planning, permissions and execution. Every consequential action must connect to a specific proposal and approval.", { flow: ["OBSERVE", "INTERPRET", "PLAN", "CHECK PERMISSIONS", "REQUEST APPROVAL", "EXECUTE", "VERIFY", "LOG", "UPDATE STATE"] }),
    block("Action tiers", "Informational actions such as explanations need no approval. Low-risk automations may run under a future explicit user policy. Consequential purchases, calls or commitments require approval bound to the action and payload."),
    block("Operational controls", "Tool interfaces limit what an agent can request. Idempotency keys prevent duplicate state-changing commands; retries need bounded policies; failures remain visible in action status and audit history. Approval tokens bind action ID, payload hash, user ID and expiry."),
  ]),
  page("ripple-engine", "Ripple Engine", "Core mechanics", "The consequence calculator at the center of the project.", "A ripple is a computed difference along typed dependencies, with an inspectable reason chain.", [
    block("Definition", "The Ripple Engine evaluates the consequences of a state change by traversing relevant dependencies and computing affected entities. Its input is a normalized change plus a state snapshot; its output is affected nodes, state differences and action candidates."),
    block("Dinner example", "Changing dinner from 6 to 10 servings changes recipe requirements, which changes effective inventory, shortages, purchases, cost exposure and potentially preparation timing.", { flow: ["DINNER  6 → 10", "RECIPE QUANTITIES", "INVENTORY REQUIREMENTS", "SHORTAGES", "PURCHASE CANDIDATES", "COST / BUDGET", "SCHEDULE"] }),
    block("Conceptual algorithm", "Rules govern which edges are relevant and how quantities are calculated. The graph gives reachability; domain services compute meaning.", { code: "change = validate(input)\naffected = traverse(relationships, change.entity)\nfor node in affected:\n  next = evaluateDomainRule(node, state, change)\n  differences.push(compare(state[node], next))\nreturn { affected, differences, actionCandidates }" }),
    block("Why an LLM is insufficient", "A model can explain a chain but should not be trusted to normalize units, reserve stock, handle duplicate events, or prove an arithmetic shortage. Deterministic calculations are reproducible and testable."),
  ]),
  page("what-if-simulation", "What-If Simulation", "Core mechanics", "Explore consequences without changing reality.", "A scenario is an isolated state fork; a commit is a separate authorized operation.", [
    block("Method", "Copy the current snapshot into an ephemeral fork, apply the hypothetical event, run the same ripple rules, then compare current and simulated values. Discard the fork after viewing, or create a new approval-backed command to commit the chosen plan.", { flow: ["CURRENT STATE", "ISOLATED FORK", "HYPOTHETICAL CHANGE", "RIPPLE ENGINE", "DIFF", "DISCARD OR APPROVE"] }),
    block("Examples", "Dinner guests 6 → 10, a trip moving by two days, subscription cancellation, vehicle service delay or a changed budget can all be modeled as scenario inputs. Only the kitchen/ripple simulation is represented in current prototype routes; the other domains are extension examples."),
  ]),
  page("verification-loop", "Verification Loop", "Core mechanics", "An action is incomplete until its outcome is known.", "Expected and observed state must be reconciled, not assumed equal.", [
    block("Closed loop", "The plan creates an expectation; a provider call or real-world activity creates an observation. A match increases confidence. A mismatch opens a review or correction path.", { flow: ["STATE", "ACTION", "REAL WORLD", "OBSERVATION", "EXPECTED vs OBSERVED", "STATE UPDATE"] }),
    block("Prototype evidence", "The API contains delivery reconciliation routes and action outcome handling. Vendor transcripts can contribute evidence. These are software-side verification mechanisms; live physical sensing is planned."),
  ]),
  page("hardware-architecture", "Hardware Architecture", "Architecture", "Physical sensing exists to correct stale digital beliefs.", "The Raspberry Pi/load-cell path is a design proposal, not a deployed integration.", [
    block("Proposed prototype", "A container rests on a calibrated load cell. An HX711/ADC translates the signal for a Raspberry Pi. Edge software samples, filters and timestamps readings, then sends a normalized observation to the backend for reconciliation.", { flow: ["CONTAINER", "LOAD CELL", "HX711 / ADC", "RASPBERRY PI", "NORMALIZED OBSERVATION", "BACKEND", "INVENTORY STATE"] }),
    block("Reliability design", "Calibration maps raw readings to mass; tare removes container weight. Samples require smoothing and bounds checks. Connectivity failures retain the last trusted value with a stale marker. Manual receipt or user correction remains available when sensing fails."),
  ]),
  page("integrations", "Integrations", "Architecture", "Adapters isolate external dependencies and their failure modes.", "Configured providers may be live; unconfigured paths and simulator fallbacks must be labeled in a demo.", [
    block("Provider map", "Secrets belong on the server, never in browser variables or examples.", { table: { columns: ["Integration", "Purpose / input → output", "Status and failure path"], rows: [["OpenAI", "Text/image/context → structured extraction or explanation", "Adapter present; key dependent; deterministic fallback in some flows"], ["Sarvam", "Audio → transcript", "Adapter present; key dependent; report unavailable input"], ["Snapserve", "Approved call request → status/transcript", "Adapter present; live or simulated mode; status polling and fallback handling"], ["PostgreSQL / Prisma", "Transactional canonical state", "Schema present; runtime migration pending"], ["pgvector", "Semantic lookup", "Planned; not active"], ["Hardware", "Weight signal → observation", "Proposed; no deployed sensor pipeline"]] } }),
    block("Operational contract", "Each adapter should declare input schema, authentication, timeout, retry behavior, rate constraints and outcome mapping. Provider rate and pricing constraints vary by account and are not hardcoded as universal limits here."),
  ]),
  page("security-and-privacy", "Security & Privacy", "Trust", "Household data and agent actions need explicit trust boundaries.", "Architecture controls are requirements; implementation claims are limited to the code present.", [
    block("Boundary", "A user request should pass authentication, authorization and policy checks before it reaches household data or an execution adapter.", { flow: ["USER", "AUTH", "APPLICATION", "PERMISSION LAYER", "DATA / AGENTS", "EXTERNAL SERVICES"] }),
    block("Implemented safeguards and gaps", "The code contains approval token binding, server-side provider secrets, schema validation, idempotency and audit records. A production-grade account authentication, role model, encrypted durable database, retention/deletion workflow and formal access revocation still require verification or implementation."),
    block("Privacy principles", "Collect the minimum data needed for a feature, scope records to a household, log consequential actions, obtain consent before external calls, protect secrets at rest and in transit, and let members review or remove sensitive data. Third-party data sharing should be made explicit at the approval point."),
  ]),
  page("reliability-and-failure-handling", "Reliability & Failure Handling", "Trust", "Failures are first-class state transitions.", "A failed provider call must not be represented as a completed household action.", [
    block("Failure matrix", "Recovery preserves a truthful state and gives the user an actionable next step.", { table: { columns: ["Failure", "Detection", "Fallback / recovery"], rows: [["AI or OCR extraction", "Invalid schema or low confidence", "Review original input; manual correction"], ["Sensor unavailable", "Missing/stale heartbeat", "Last trusted state with stale flag; manual update"], ["External API down", "Timeout or error", "Bounded retry; show pending/failed; no false completion"], ["Duplicate event", "Idempotency key", "Return prior result, avoid double mutation"], ["Conflicting observations", "Expected/observed mismatch", "Reconciliation queue and audit trail"], ["Rejected action", "Explicit user decision", "Close proposal without execution"], ["Network or transaction failure", "Request/commit error", "Retry safely after state read; retain prior state"]] } }),
    block("Communication rule", "Explain what was observed, what remains uncertain and what the user can do. Do not hide a simulator result behind language that implies a real vendor completed the action."),
  ]),
  page("business-model", "Business Model", "Strategy", "Monetization paths are hypotheses to test.", "The prototype has no verified paid revenue.", [
    block("Potential model", "A household subscription could fund the core state workspace; premium tiers might add advanced automation or integrations. Transaction fees on approved purchases and optional hardware are separate future paths, dependent on partner terms and user trust."),
    block("Unit economics questions", "Pricing must exceed cloud, model, speech, support and integration costs while leaving a clear user benefit. Validate willingness to pay, recurring engagement, provider usage, purchase conversion and hardware support cost before claiming a scalable margin."),
  ]),
  page("market-opportunity", "Market Opportunity", "Strategy", "Use a bottom-up model before quoting a large market.", "No TAM, SAM or SOM amount is presented as measured today.", [
    block("TAM / SAM / SOM method", "TAM = addressable households × plausible annual revenue per household. SAM narrows to supported geographies, languages, devices and purchasing behaviors. SOM applies a realistic reach and adoption assumption to SAM. Every variable should come from a cited population source or measured pilot data."),
    block("Initial segment", "The first likely segment is multi-person, smartphone-using households that shop regularly and coordinate meals. India is a practical starting geography for English/Tamil voice workflows, but payment behavior and acquisition costs need primary validation."),
    block("Expansion logic", "Cross-domain use increases value only if the kitchen wedge earns trust and the data model supports additional obligations without disproportionate setup burden."),
  ]),
  page("competitive-landscape", "Competitive Landscape", "Strategy", "Compare architectural dimensions, not absolute superiority claims.", "The proposed distinction is the combined state → ripple → simulation → approved action → verification loop.", [
    block("Category map", "Individual products vary. This table compares common category emphasis rather than claiming no competitor offers a feature.", { table: { columns: ["Category", "Common strength", "Relevant gap to evaluate"], rows: [["AI assistants", "Language interaction", "Durable shared state and verified actions"], ["Task/calendar tools", "Scheduling", "Resource dependencies"], ["Smart-home platforms", "Device automation", "Cross-service planning"], ["Grocery/inventory apps", "Stock and lists", "Obligation graph beyond kitchen"], ["Family organizers", "Shared coordination", "Simulation and physical reconciliation"], ["Automation platforms", "Workflow execution", "Household-specific causal model"]] } }),
    block("Claim discipline", "The prototype demonstrates selected pieces of this combination; broad competitive advantage and user preference still require comparative testing."),
  ]),
  page("sdg-alignment", "SDG Alignment", "Strategy", "Designed to support more responsible household resource use.", "Potential contribution is plausible; impact has not yet been measured.", [
    block("Primary · SDG 12", "Inventory awareness, shortage-based purchasing and expiry visibility may reduce duplicate buying and improve resource utilization. A pilot would need baseline waste and purchase measurements to establish an actual effect."),
    block("Secondary · SDG 9 and 11", "The system explores digital infrastructure connecting household services and a more coordinated urban living experience. These are contextual alignments, not measured outcomes."),
  ]),
  page("roadmap", "Roadmap", "Delivery", "A sequence of proof, hardening and expansion.", "Later phases are proposals and depend on measured success in the first domain.", [
    block("Phase 1 · Prototype", "Kitchen receipt, inventory, meal simulation, ripple trace, approval and action verification. Success: a judge can follow a complete, truthful demo path with a visible reason chain."),
    block("Phase 2 · Household domains", "Add typed vehicle, document, subscription and scheduling entities. Success: a cross-domain ripple can be tested without hardcoded special cases."),
    block("Phase 3 · Integrations", "Move runtime state to PostgreSQL, strengthen authentication and add reliable provider/webhook operations. Success: durable multi-user state and recoverable external actions."),
    block("Phase 4 · Physical intelligence", "Prototype calibrated sensor observations and reconciliation. Success: measured sensor error bounds and graceful offline behavior."),
    block("Phase 5 · Ecosystem", "Explore partner tools and multi-household workflows only after privacy, permissions and core retention are validated."),
  ]),
  page("metrics-and-kpis", "Metrics & KPIs", "Delivery", "Define success before claiming it.", "The documentation does not invent current values.", [
    block("Product metrics", "Track inventory accuracy against manual audits, median state age, extraction success, simulation accuracy, approval rate, action success, verification coverage, reconciliation rate, recommendation acceptance and user-reported time saved. Each needs an explicit denominator and measurement window."),
    block("Technical metrics", "Track p50/p95 API latency, agent execution time, error rate, database response time, duplicate-event rate and sensor availability. Current target values are to be set after baseline measurement."),
    block("Business metrics", "Track activation, cohort retention, paid conversion, ARPU, CAC, LTV and churn only after real acquisition and payment experiments. Status today: not yet measured."),
  ]),
  page("limitations", "Limitations", "Delivery", "A credible prototype states its unfinished edges.", "The most important next step is durable, secure state in a real multi-user environment.", [
    block("Current limits", "The strongest vertical is kitchen. Runtime state is file backed, with ephemeral hosted storage risk; PostgreSQL and pgvector are not the active canonical runtime. Provider behavior depends on credentials and may use fallbacks. Physical sensors are conceptual. A complete household domain graph, production account roles and broad market validation are outstanding."),
    block("Product risks", "Cold start requires useful household data; people must trust both recommendations and privacy boundaries. Estimates can drift from reality. Consequential automation must remain narrow and reversible where possible. Sensors need calibration and cannot be treated as infallible."),
  ]),
  page("future-scope", "Future Scope", "Delivery", "Extend the state model only where the dependency graph adds value.", "Every item here is an expansion possibility, not a present feature claim.", [
    block("Possible domains", "Vehicles, documents, subscriptions, travel, appointments, home maintenance, family coordination and financial planning can reuse the same event/state/ripple structure with domain-specific rules."),
    block("Possible capabilities", "More multilingual interfaces, calibrated physical sensing, predictive planning and specialized agents could reduce manual updates. Each requires data consent, evaluation, fallback behavior and a clear approval boundary."),
  ]),
  page("demo-guide", "Demo Guide", "Judge resources", "A two-minute trace through the complete kitchen loop.", "Show what the system calculates, what a human approves and what is verified.", [
    block("Suggested walkthrough", "1. Open the household dashboard and inspect current pantry state. 2. Upload a receipt and review extracted lines before confirming. 3. Ask for a meal for a given serving count. 4. Open the what-if simulation and increase guests. 5. Inspect shortages and the Why trace. 6. Review the proposed vendor action. 7. Approve and show live or clearly labeled simulated Snapserve status. 8. Reconcile a delivery observation and inspect updated state/history."),
    block("Judge checkpoints", "At each step point to input, state before/after, deterministic calculation, approval boundary and evidence. If a provider is unavailable, identify the fallback visibly and continue through the same contract."),
  ]),
  page("judge-q-and-a", "Judge Q&A", "Judge resources", "Direct answers to the hardest evaluation questions.", "The project is strongest when novelty and limitations are explained together.", [
    block("What is novel?", "The architectural combination of shared household state, typed dependencies, deterministic ripple calculation, isolated simulation, approval-bound action and outcome verification. It is a product thesis demonstrated first in the kitchen."),
    block("Why use an LLM?", "For messy human inputs and explanations. Calculations and permissions remain deterministic. A model response never by itself authorizes a purchase."),
    block("Is the database production ready?", "No. Prisma describes a PostgreSQL target, while the current runtime uses a JSON-backed store. Durable transactional persistence and multi-user authorization are major next steps."),
    block("Is the hardware real?", "The proposed load-cell/Raspberry Pi path is documented architecture. The current proof relies on software observations and reconciliations."),
    block("How do you know an action worked?", "The action records an expectation and waits for provider status, transcript or delivery evidence. A mismatch should remain visible and trigger reconciliation."),
  ]),
  page("technical-setup", "Technical Setup", "Engineering reference", "Run the prototype from the monorepo.", "Local startup proves a working prototype; provider behavior depends on configuration.", [
    block("Requirements and commands", "Use Node 22 or newer and pnpm 10. Copy .env.example to .env locally and configure server-side keys only when testing external integrations.", { code: "pnpm install\npnpm dev:api\npnpm dev\npnpm typecheck\npnpm --filter @household/web build" }),
    block("Runtime notes", "The API defaults to port 4000. The local file-backed state lives under the API working directory's .data path unless configured otherwise. Do not commit .env, state files or provider credentials. Inspect /api/health and /api/ready to see service health/configuration."),
  ]),
  page("api-documentation", "API Documentation", "Engineering reference", "A selected route map for the judge-critical path.", "Shared Zod contracts define request and response shapes; inspect the source for the complete route contract.", [
    block("Core routes", "These routes are present in apps/api/src/app.ts. Authentication and deployment behavior should be checked in the target environment.", { table: { columns: ["Method", "Path", "Purpose"], rows: [["GET", "/api/dashboard", "Household overview"], ["GET", "/api/inventory", "Current resources"], ["POST", "/api/receipts/extract", "Extract receipt candidate"], ["POST", "/api/receipts/:id/confirm", "Commit reviewed receipt"], ["POST", "/api/meals/simulate", "Compare meal requirements"], ["POST", "/api/ripple/simulate", "Counterfactual ripple"], ["GET", "/api/why/:itemId", "Reason chain"], ["POST", "/api/actions/:id/approve", "Authorize and execute bounded action"], ["POST", "/api/verification/reconcile-delivery", "Reconcile observed delivery"], ["GET", "/api/activity", "Activity history"]] } }),
    block("Command conventions", "Validate payloads against shared contracts, include an idempotency key on state-changing commands, and treat approval as a distinct trust boundary. Never send provider keys from the browser."),
  ]),
  page("database-documentation", "Database Documentation", "Engineering reference", "A relational target schema alongside a prototype runtime store.", "The schema is a design asset; it is not evidence that the current API writes to PostgreSQL.", [
    block("Schema groups", "Household and Member scope ownership. Resource and InventoryLot model quantities. ReceiptUpload records intake. Recipe, RecipeIngredient and MealPlan model demand. Event and Relationship support propagation. Action, ActionOutcome and audit tables support execution evidence.", { flow: ["HOUSEHOLD → MEMBER", "RESOURCE → INVENTORY LOT", "RECIPE → RECIPE INGREDIENT", "EVENT → RELATIONSHIP", "ACTION → ACTION OUTCOME", "STATE SNAPSHOT → AUDIT LOG"] }),
    block("Migration requirement", "A production move needs transactions, tenant isolation, idempotency constraints, migrations, snapshot strategy and parity tests against domain-engine behavior. Vector indexes can aid retrieval but cannot replace relational facts."),
  ]),
  page("development-phases", "Development Phases", "Engineering reference", "From demo loop to durable household system.", "Each phase has an observable exit criterion.", [
    block("Build sequence", "1. Establish shared contracts and seed data. 2. Implement deterministic inventory, meal and ripple logic. 3. Expose API workflows. 4. Build desktop/mobile journey. 5. Add provider adapters and approval boundaries. 6. Validate failure handling and traceability. 7. Migrate durable state and expand domains."),
    block("Current checkpoint", "The checked-in repository includes phases one through five in prototype form, with some tests and adapter fallbacks. Production persistence, security hardening, hardware validation and market experiments remain open work."),
  ]),
  page("team-contributions", "Team Contributions", "Engineering reference", "A transparent contribution record for judges.", "Named ownership should be filled from the team’s actual records before submission.", [
    block("Workstreams", "The repository’s AGENTS.md describes frontend, backend, AI, integration and QA/security ownership lanes. Those are workstream boundaries, not verified individual credit. Use commit history and team confirmation to attribute people to design, domain engines, API, adapters, demo and testing."),
    block("Suggested evidence", "Link a contributor to concrete commits, reviewed PRs, test artifacts or demo segments. Avoid inventing names or percentages."),
  ]),
  page("references-and-sources", "References & Sources", "Engineering reference", "Source material and claim boundaries.", "Implementation claims should be traceable to repository code; external impact claims require independent evidence.", [
    block("Primary project sources", "The authoritative local documents are docs/PRD.md, docs/TRD.md, docs/DESIGN_SYSTEM.md and AGENTS.md. Runtime details are in apps/api/src/app.ts, packages/domain, packages/db/src/index.ts, packages/db/prisma/schema.prisma and packages/integrations."),
    block("External references", "Use official provider documentation for API behavior and official UN material for SDG framing. The portal avoids unsourced market totals and measured environmental impact claims.", { points: ["United Nations Sustainable Development Goal 12 — un.org/sustainabledevelopment/sustainable-consumption-production/", "OpenAI API documentation — platform.openai.com/docs", "PostgreSQL documentation — postgresql.org/docs/", "Prisma documentation — prisma.io/docs/"] }),
  ]),
  page("glossary", "Glossary", "Engineering reference", "A shared vocabulary for product and engineering review.", "Use these terms consistently when presenting the system.", [
    block("Core terms", "Household state: current, evidence-backed representation of a household. Event: a normalized occurrence that may alter state. Relationship: a typed dependency between entities. Ripple: computed consequences of a change. Simulation: isolated hypothetical state. Observation: an external or physical signal. Reconciliation: comparing expected and observed outcomes."),
    block("Action terms", "Proposal: candidate action with reason chain. Approval token: bounded authorization for one action/payload/user/expiry. Idempotency key: client-provided identifier that prevents duplicate command effects. Canonical state: the authoritative persisted record, independent of any agent conversation."),
  ]),
];

export const docGroups = ["Start here", "Product", "Architecture", "Core mechanics", "Trust", "Strategy", "Delivery", "Judge resources", "Engineering reference"];
