// Vercel serves every /api/* request through this one function (see the
// rewrites in vercel.json). _server.cjs is the bundled API, generated by
// scripts/build-api.mjs, so it is not committed.
const server = require("./_server.cjs");
module.exports = server.default || server;
